# azure-pipelines.yml

trigger:
- master  # Trigger the pipeline on commits to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent for this pipeline

steps:
- script: echo 'Starting the build process...'  # A simple script step
  displayName: 'Starting Build'

- task: DotNetCoreCLI@2  # Use DotNetCoreCLI task to build a .NET Core application
  inputs:
    command: 'build'
    projects: '**/*.csproj'  # Path to your .csproj file(s)

- script: echo 'Build completed successfully!'  # Another script step
  displayName: 'Build Successful'
